# Custom iOS Podfile with Appodeal Exclusive Mediation (No Google AdMob)

platform :ios, '15.0'

# Appodeal custom CocoaPods sources
source 'https://github.com/appodeal/CocoaPods.git'
source 'https://github.com/bidon-io/CocoaPods-Specs.git'
source 'https://cdn.cocoapods.org'

install! 'cocoapods', :deterministic_uuids => false, :warn_for_multiple_pod_sources => false

flutter_root = File.expand_path('..', File.dirname(__FILE__))

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Core Appodeal SDK and selected non-AdMob adapters
  pod 'Appodeal', '4.2.0'
  pod 'AppodealAppLovinAdapter', '13.5.1.0'
  pod 'AppodealIronSourceAdapter', '9.1.0.0'
  pod 'AppodealUnityAdsAdapter', '4.17.0.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
